### ISSUE TITLE
increase minimum-quality default to 19?

### ISSUE THREAD

**Issue by gregcaporaso** [wasade/q2-quality-filter#2]
I think going with a `minimum-quality` default of 19 makes sense here, as this data is intended to go directly into deblur and that's what's used in the deblur paper. I don't see a real reason to match the QIIME 1 default of 3 here, I think it's too low. Is there another motivation to keep it at 3?

**Comment by wasade** [comment]
Just to match the existing defaults

**Comment by gregcaporaso** [comment]
Are you good with changing? I think it's more important to match the deblur paper than QIIME 1 at this point.
