### ISSUE TITLE
have the results of this quality filter been compared to QIIME 1 split_libraries_fastq?

### ISSUE THREAD

**Issue by gregcaporaso** [wasade/q2-quality-filter#5]
Do we expect that the results of the quality filtering will be identical when the same parameters are used? If so, have the results been compared between this plugin and QIIME 1's `split_libraries_fastq.py`?

**Comment by wasade** [comment]
Yes in that this should be deterministic, and based on the previous `workflow` code, I do think that the seqs will be identical. I do not know whether the logging stats will be comparable as we're now tracking with increased specificity.

**Comment by wasade** [comment]
Just a reminder here about the PHRED score metadata issue with the MVP data. The `demux.qza` for the tutorial indicates offset of 33 but it is actually 64.
